# DÃ©finition d'un tableau de routes au format TOML (https://toml.io/)
# - url : chemin dans l'URL
# - controleur : chemin vers le fichier du controleur
# - template : chemin vers le fichier de template

[[routes]]
url = ""
controleur = "controleurs/accueil.py"
template = "accueil.html"

[[routes]]
url = "regles"
controleur = "controleurs/regles.py"
template = "regles.html"

[[routes]]
url = "statistiques"
controleur = "controleurs/statistiques.py"
template = "statistiques.html"

[[routes]]
url = "classements"
controleur = "controleurs/classements.py"
template = "classements.html"

[[routes]]
url = "parties"
controleur = "controleurs/parties.py"
template = "parties.html"

[[routes]]
url = "jeu"
controleur = "controleurs/jeu.py"
template = "jeu.html"