# fichier de configuration au SGBD postgreSQL

POSTGRESQL_SERVER = "bd-pedago.univ-lyon1.fr"
POSTGRESQL_USER = "p1234567"
POSTGRESQL_PASSWORD = "remplace42moi" 
POSTGRESQL_DATABASE = "p1234567"
POSTGRESQL_SCHEMA = "projetbdw"

# p2303380 9BHXHrmxCsAc